### ISSUE TITLE
CircleCIでテストを実行する準備（techpit第3章の設定）

### ISSUE THREAD

**Issue by nakatievent** [nakatievent/my_baby_diary_app#61]
## `CircleCI`でテストを実行する準備

`techpit`でのテストの実装は一旦置いといて、`CircleCI`でテストを実行する準備を整えることにする

**参考**
[3章 : CircleCIでテストを実行しよう](https://www.techpit.jp/courses/78/curriculums/81/sections/617/parts/2099)

**Comment by nakatievent** [comment]
## `.circleci/config.yml`ファイルに下記の記述を追加する

```
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
```
